---
services: docker

env:
  - distro: centos7
  - distro: fedora27
  - distro: ubuntu1604
  - distro: ubuntu1710
  - distro: ubuntu1804

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim
  - wget -O ${PWD}/tests/test.sh https://gist.github.com/brentwg/64f90bdda32a51360f71558d3171fcbb/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests
  - ${PWD}/tests/test.sh

  # Test that additional packages tasks fired (check pass)
  - docker exec --tty $container_id env TERM=xterm pass --version

  # Test that package groups tasks fired (check gcc)
  - docker exec --tty $container_id env TERM=xterm gcc --version

  # Test that virtualization packages installed (check virsh)
  - docker exec --tty $container_id env TERM=xterm virsh --version

  # Test that NOPASSWD sudo is enabled
  - docker exec --tty $container_id env TERM=xterm grep NOPASSWD /etc/sudoers | grep -v '#'

  # Test SSH Server tasks fired (check sshd_config)
  - docker exec --tty $container_id env TERM=xterm egrep '^PermitRootLogin no' /etc/ssh/sshd_config

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
