---
- name: Install additional packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ additional_packages }}"

- name: Install additional group packages (Fedora)
  dnf:
    name: "@{{ item }}"
    state: present
  with_items: "{{ additional_groups }}"
  when: ansible_distribution == 'Fedora'

- name: Install additional group packages (CentOS)
  yum:
    name: "@{{ item }}"
    state: present
  with_items: "{{ additional_groups }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
