---
# Variable configuration
- import_tasks: variables.yml

# Deal with additional packages
- name: Install additional packages (ALL)
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ additional_packages }}"

# Task Configuration
- name: Include OS-specific tasks
  include_tasks: "{{ task_item }}"
  with_first_found: 
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: true
  loop_control:
    loop_var: task_item

# Deal with SSH Server (ALL)
- name: Install SSH server
  package:
    name: "{{ ssh_server_package }}"
    state: present

- name: Enable SSH server
  service:
    name: "{{ ssh_service_name }}"
    enabled: yes

- name: Disable root access
  lineinfile:
    dest: "{{ ssh_sshd_config }}"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify:
    - restart ssh server

- name: Disallow GSS API authentication
  lineinfile:
    dest: "{{ ssh_sshd_config }}"
    regexp: "^GSSAPIAuthentication"
    line: "GSSAPIAuthentication no"
    state: present
  notify:
    - restart ssh server
