---
# Variable configuration
- import_tasks: variables.yml

- import_tasks: additional_packages.yml

- import_tasks: ssh_server.yml

- import_tasks: selinux.yml
  when: ansible_os_family == "RedHat"

- import_tasks: sudo_nopasswd.yml
