---
# Variable configuration
- import_tasks: variables.yml

# Add additional packages
- import_tasks: additional_packages.yml

# Enable SSH server
- import_tasks: ssh_server.yml

# Disable SELinux
- import_tasks: selinux.yml
  when: ansible_os_family == "RedHat"

# Enable nopasswd sudo 
- import_tasks: sudo_nopasswd.yml

# Configure Plymouth boot theme
- import_tasks: plymouth_boot_theme.yml
  when: ansible_os_family == "RedHat"
  