---
# Variable configuration
- import_tasks: variables.yml

# Deal with additional packages
- name: Install additional packages (ALL)
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ additional_packages }}"

# Task Configuration
- name: Include OS-specific tasks
  include_tasks: "{{ task_item }}"
  with_first_found: 
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: true
  loop_control:
    loop_var: task_item

# Deal with SSH Server
- include tasks: ssh_server.yml
