---
- name: Install the Spinfinity theme (RedHat)
  package:
    name: plymouth-theme-spinfinity
    state: present

- name: Register current running theme (RedHat)
  shell: egrep ^Theme= /etc/plymouth/plymouthd.conf | awk -F'[=]' '{ print $2 }'
  register: egrep_output

- name: Enable the Spinfinity theme and rebuild initrd (RedHat)
  shell: plymouth-set-default-theme spinfinity -R
  when: egrep_output.stdout != spinfinity
  